version: "3.9"
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - keploy-network
networks:
  keploy-network:
    external: true
