version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres-keploy-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - keploy-network
networks:
  keploy-network:
    external: true
